import fs from "node:fs";
import path from "node:path";
import propertyDefinitions from "../lib/generated/propertyDefinitions.js";

const { dirname } = import.meta;

const list = fs
  .readdirSync(path.resolve(dirname, "../lib/properties"))
  .map((file) => [file.replace(/\.js$/, ""), file]);
const implementedProperties = new Map(list);

const requires = [];
const descriptors = [];
for (const [canonicalProperty, { legacyAliasOf, styleDeclaration }] of propertyDefinitions) {
  const camelizedProperty = dashedToCamelCase(canonicalProperty);
  const camelizedAliasProperty = legacyAliasOf ? dashedToCamelCase(legacyAliasOf) : "";
  if (implementedProperties.has(camelizedProperty)) {
    requires.push(
      `const ${camelizedProperty} = require("../properties/${implementedProperties.get(camelizedProperty)}");`
    );
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${camelizedProperty}.descriptor`);
    }
  } else if (implementedProperties.has(camelizedAliasProperty)) {
    // No need to add to `requires` since the non-alias branch of the outer loop
    // will ensure the corresponding handler file is included there.
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${camelizedAliasProperty}.descriptor`);
    }
  } else {
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": createGenericPropertyDescriptor("${canonicalProperty}")`);
    }
  }
}

const [dateTodayFormatted] = new Date().toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

${requires.sort().join("\n")}
const { createGenericPropertyDescriptor } = require("../utils/propertyDescriptors.js");

module.exports = {
  ${descriptors.join(",\n  ")}
};
`;

fs.writeFileSync(path.resolve(dirname, "../lib/generated/propertyDescriptors.js"), output);

// Utility to translate from `border-width` to `borderWidth`.
// NOTE: For values prefixed with webkit, e.g. `-webkit-foo`, we need to provide
// both `webkitFoo` and `WebkitFoo`. Here we only return `webkitFoo`.
function dashedToCamelCase(dashed) {
  if (dashed.startsWith("--")) {
    return dashed;
  }
  let camel = "";
  let nextCap = false;
  // skip leading hyphen in vendor prefixed value, e.g. -webkit-foo
  let i = /^-webkit-/.test(dashed) ? 1 : 0;
  for (; i < dashed.length; i++) {
    if (dashed[i] !== "-") {
      camel += nextCap ? dashed[i].toUpperCase() : dashed[i];
      nextCap = false;
    } else {
      nextCap = true;
    }
  }
  return camel;
}
