import fs from "node:fs";
import path from "node:path";
import css from "@webref/css";

const { properties } = await css.listAll();
const definitions = properties.map((definition) => [definition.name, definition]);

const [dateTodayFormatted] = new Date().toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

module.exports = new Map(${JSON.stringify(definitions, null, 2)});
`;

const { dirname } = import.meta;
const dir = path.resolve(dirname, "../lib/generated/");
if (!fs.existsSync(dir)) {
  fs.mkdirSync(dir, {
    recursive: true
  });
}
fs.writeFileSync(path.resolve(dir, "propertyDefinitions.js"), output);
