import fs from "node:fs";
import path from "node:path";
import { camelCaseToDashed } from "../lib/utils/camelize.js";

const { dirname } = import.meta;
const dashedProperties = fs
  .readdirSync(path.resolve(dirname, "../lib/properties"))
  .filter((propertyFile) => path.extname(propertyFile) === ".js")
  .map((propertyFile) => camelCaseToDashed(path.basename(propertyFile, ".js")));

const outputFile = path.resolve(dirname, "../lib/generated/implementedProperties.js");

const propertyNamesJSON = JSON.stringify(dashedProperties.toSorted(), undefined, 2);
const dateToday = new Date();
const [dateTodayFormatted] = dateToday.toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}
// https://www.w3.org/Style/CSS/all-properties.en.html

module.exports = new Set(${propertyNamesJSON});
`;

fs.writeFileSync(outputFile, output);
