import fs from "node:fs";
import path from "node:path";
import { camelCaseToDashed } from "../lib/utils/camelize.js";

const { dirname } = import.meta;

const list = fs.readdirSync(path.resolve(dirname, "../lib/properties")).map((file) => {
  return file.replace(/\.[cm]?js$/, "");
});

const requires = [];
const moduleExports = [];
for (const property of list) {
  const dashedProperty = camelCaseToDashed(property);
  requires.push(`const ${property} = require("../properties/${property}");`);
  moduleExports.push(`["${dashedProperty}", ${property}]`);
}

const outputFile = path.resolve(dirname, "../lib/generated/propertyHandlers.js");

const dateToday = new Date();
const [dateTodayFormatted] = dateToday.toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

${requires.join("\n")}

module.exports = new Map([
  ${moduleExports.sort().join(",\n  ")}
]);
`;

fs.writeFileSync(outputFile, output);
