import fs from "node:fs";
import path from "node:path";
import propertyDefinitions from "../lib/generated/propertyDefinitions.js";
import { dashedToCamelCase } from "./camelize.mjs";

const { dirname } = import.meta;

const list = fs
  .readdirSync(path.resolve(dirname, "../lib/properties"))
  .map((file) => file.replace(/\.js$/, ""));
const camelCasedProperties = new Set(list);

const requires = [];
const descriptors = [];
for (const [canonicalPropertyName, { styleDeclaration }] of propertyDefinitions) {
  const camel = dashedToCamelCase(canonicalPropertyName);
  if (camelCasedProperties.has(camel)) {
    requires.push(`const ${camel} = require("../properties/${camel}");`);
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${camel}.definition`);
    }
  } else {
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": getPropertyDescriptor("${canonicalPropertyName}")`);
    }
  }
}

const outputFile = path.resolve(dirname, "../lib/generated/propertyDescriptors.js");

const dateToday = new Date();
const [dateTodayFormatted] = dateToday.toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

${requires.sort().join("\n")}
const { getPropertyDescriptor } = require("../utils/propertyDescriptors.js");

module.exports = {
  ${descriptors.join(",\n  ")}
};
`;

fs.writeFileSync(outputFile, output);
