import fs from "node:fs";
import path from "node:path";
import propertyDefinitions from "../lib/generated/propertyDefinitions.js";
import { dashedToCamelCase } from "./camelize.mjs";

const { dirname } = import.meta;

const list = fs
  .readdirSync(path.resolve(dirname, "../lib/properties"))
  .map((file) => [file.replace(/\.js$/, ""), file]);
const implementedProperties = new Map(list);

const requires = [];
const descriptors = [];
for (const [canonicalPropertyName, { legacyAliasOf, styleDeclaration }] of propertyDefinitions) {
  const camel = dashedToCamelCase(canonicalPropertyName);
  const aliasCamel = legacyAliasOf ? dashedToCamelCase(legacyAliasOf) : "";
  if (implementedProperties.has(camel)) {
    requires.push(`const ${camel} = require("../properties/${implementedProperties.get(camel)}");`);
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${camel}.definition`);
    }
  } else if (implementedProperties.has(aliasCamel)) {
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${aliasCamel}.definition`);
    }
  } else {
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": getPropertyDescriptor("${canonicalPropertyName}")`);
    }
  }
}

const [dateTodayFormatted] = new Date().toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

${requires.sort().join("\n")}
const { getPropertyDescriptor } = require("../utils/propertyDescriptors.js");

module.exports = {
  ${descriptors.join(",\n  ")}
};
`;

fs.writeFileSync(path.resolve(dirname, "../lib/generated/propertyDescriptors.js"), output);
