import fs from "node:fs";
import path from "node:path";
import { camelCaseToDashed } from "./camelize.mjs";

const { dirname } = import.meta;

const list = fs.readdirSync(path.resolve(dirname, "../lib/properties")).map((file) => {
  return file.replace(/\.[cm]?js$/, "");
});

const requires = [];
const handlers = [];
for (const property of list) {
  const dashedProperty = camelCaseToDashed(property);
  requires.push(`const ${property} = require("../properties/${property}");`);
  handlers.push(`["${dashedProperty}", ${property}]`);
}

const outputFile = path.resolve(dirname, "../lib/generated/propertyHandlers.js");

const dateToday = new Date();
const [dateTodayFormatted] = dateToday.toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

${requires.join("\n")}
const { getPropertyDescriptor } = require("../utils/propertyDescriptors");
const propertyDefinitions = require("./propertyDefinitions");

const implementedHandlers = new Map([
  ${handlers.sort().join(",\n  ")}
]);

const getHandler = (property) => {
  if (implementedHandlers.has(property)) {
    return implementedHandlers.get(property).definition;
  }
  return getPropertyDescriptor(property);
};

const preparePropertyHandlers = () => {
  const propertyHandlers = new Map();
  for (const [key, value] of propertyDefinitions.entries()) {
    const { styleDeclaration } = value;
    const handler = getHandler(key);
    if (handler) {
      for (const property of styleDeclaration) {
        propertyHandlers.set(property, handler);
      }
    }
  }
  return propertyHandlers;
};

module.exports = {
  propertyHandlers: Object.fromEntries(preparePropertyHandlers())
};
`;

fs.writeFileSync(outputFile, output);
