'use strict';

const fs = require('fs');
const path = require('path');

const { idlAttributeToCSSProperty } = require('../lib/parsers');

const webkitPropertyName = /^webkit[A-Z]/;
const outputFilePath = path.resolve(__dirname, '../lib/implementedProperties.js');
const stream = fs.createWriteStream(outputFilePath);

stream.write(
  `'use strict';\n\n// autogenerated by scripts/generate_implemented_properties.js - ${new Date().toISOString()}}'\n`
);
stream.write('module.exports = new Set([\n');
fs.readdirSync(path.resolve(__dirname, '../lib/properties'))
  .filter(propertyFile => path.extname(propertyFile) === '.js')
  .forEach(propertyFile => {
    const dashPrefix = webkitPropertyName.test(propertyFile);
    const camelcase = path.basename(propertyFile, '.js');
    const property = idlAttributeToCSSProperty(camelcase, dashPrefix);
    stream.write(`\t'${property}',\n`);
  });
stream.write(']);\n');
stream.end(err => {
  if (err) {
    throw err;
  }
});
