import fs from "node:fs";
import path from "node:path";
import css from "@webref/css";
import allProperties from "../lib/generated/allProperties.js";
import allExtraProperties from "../lib/utils/allExtraProperties.js";

const unifiedProperties =
  typeof allProperties.union === "function"
    ? allProperties.union(allExtraProperties)
    : new Set([...allProperties, ...allExtraProperties]);

const { properties } = await css.listAll();
const definitions = new Map();
if (Array.isArray(properties)) {
  for (const definition of properties) {
    const { href, initial, inherited, computedValue, legacyAliasOf, name, styleDeclaration } =
      definition;
    if (unifiedProperties.has(name)) {
      definitions.set(name, {
        href,
        initial,
        inherited,
        computedValue,
        legacyAliasOf,
        name,
        styleDeclaration
      });
    }
  }
}

const propertyList = new Map();
for (const property of [...unifiedProperties].toSorted()) {
  const definition = definitions.get(property);
  if (definition) {
    propertyList.set(property, definition);
  }
}
const [dateTodayFormatted] = new Date().toISOString().split("T");
const output = `"use strict";
// autogenerated - ${dateTodayFormatted}

module.exports = new Map(${JSON.stringify([...propertyList], null, 2)});
`;
const { dirname } = import.meta;
const outputFile = path.resolve(dirname, "../lib/generated/propertyList.js");
fs.writeFileSync(outputFile, output);
