import fs from "node:fs";
import path from "node:path";
import css from "@webref/css";

const { dirname } = import.meta;
const [dateTodayFormatted] = new Date().toISOString().split("T");

const { properties, types } = await css.listAll();
const propertyDefinitions = properties.map((definition) => [definition.name, definition]);
const syntaxDefinitions = types.map((definition) => [`<${definition.name}>`, definition]);

const propertyOutput = `"use strict";
// autogenerated - ${dateTodayFormatted}

module.exports = new Map(${JSON.stringify(propertyDefinitions, null, 2)});
`;
const syntaxOutput = `"use strict";
// autogenerated - ${dateTodayFormatted}

module.exports = new Map(${JSON.stringify(syntaxDefinitions, null, 2)});
`;

fs.writeFileSync(path.resolve(dirname, "../lib/generated/propertyDefinitions.js"), propertyOutput);
fs.writeFileSync(path.resolve(dirname, "../lib/generated/syntaxDefinitions.js"), syntaxOutput);
