import fs from "node:fs/promises";
import path from "node:path";
import css from "@webref/css";
import { definitionSyntax } from "css-tree";

const { dirname } = import.meta;
const outputDir = path.resolve(dirname, "../lib/generated");
const propertyFiles = await fs.readdir(path.resolve(dirname, "../lib/properties"));
const implementedProperties = new Map(propertyFiles.map((file) => [file.replace(/\.js$/, ""), file]));

const [dateToday] = new Date().toISOString().split("T");
const fileHeader = `"use strict";
// autogenerated - ${dateToday}
`;

const { properties, types } = await css.listAll();
const definitions = new Map(
  properties.map((definition) => {
    delete definition.extended;
    return [definition.name, definition];
  })
);
const syntaxes = new Map(types.map((definition) => [`<${definition.name}>`, definition]));

const caseSensitiveTypes = ["custom-ident", "dashed-ident", "string"];
const dimensionTypes = [
  "angle",
  "angle-percentage",
  "flex",
  "frequency",
  "frequency-percentage",
  "integer",
  "length",
  "length-percentage",
  "number",
  "percentage",
  "ratio",
  "time",
  "time-percentage"
];
const functionTypes = ["color", "image", "paint"];
const typeList = new Set([...caseSensitiveTypes, ...dimensionTypes, ...functionTypes]);

await Promise.all([generateDefinitions(), generateDescriptors()]);

/**
 * Generates property definitions file.
 *
 * @returns {Promise<void>}
 */
function generateDefinitions() {
  const output = `${fileHeader}
module.exports = new Map(${JSON.stringify([...definitions], null, 2)});
`;
  return fs.writeFile(path.resolve(outputDir, "propertyDefinitions.js"), output);
}

/**
 * Generates property descriptors file.
 *
 * @returns {Promise<void>}
 */
function generateDescriptors() {
  const requires = [];
  const descriptors = [];
  for (const [canonicalProperty, { legacyAliasOf, styleDeclaration, syntax }] of definitions) {
    const camelizedProperty = dashedToCamelCase(canonicalProperty);
    const camelizedAliasProperty = legacyAliasOf ? dashedToCamelCase(legacyAliasOf) : "";
    let descriptorSource;
    if (implementedProperties.has(camelizedProperty)) {
      const fileName = implementedProperties.get(camelizedProperty);
      requires.push(`const ${camelizedProperty} = require("../properties/${fileName}");`);
      descriptorSource = `${camelizedProperty}.descriptor`;
    } else if (implementedProperties.has(camelizedAliasProperty)) {
      // No need to add to `requires` since the non-alias branch of the outer
      // loop will ensure the corresponding handler file is included there.
      descriptorSource = `${camelizedAliasProperty}.descriptor`;
    } else {
      const opts = JSON.stringify(createDescriptorOpts(syntax));
      descriptorSource = `createGenericPropertyDescriptor("${canonicalProperty}", ${opts})`;
    }
    for (const property of styleDeclaration) {
      descriptors.push(`"${property}": ${descriptorSource}`);
    }
  }
  const output = `${fileHeader}
${requires.sort().join("\n")}
const { createGenericPropertyDescriptor } = require("../utils/propertyDescriptors.js");

module.exports = {
  ${descriptors.join(",\n  ")}
};
`;
  return fs.writeFile(path.resolve(outputDir, "propertyDescriptors.js"), output);
}

/**
 * Creates property descriptor options.
 *
 * @param {string} syntax - The CSS syntax definition.
 * @returns {object} The property descriptor options object.
 */
function createDescriptorOpts(syntax) {
  const opts = {
    caseSensitive: false
  };
  const collectedTypes = collectTypes(syntax);
  if (!collectedTypes.size) {
    return opts;
  }
  for (const type of caseSensitiveTypes) {
    if (collectedTypes.has(type)) {
      opts.caseSensitive = true;
      break;
    }
  }
  const dimensions = {};
  for (const key of dimensionTypes) {
    if (collectedTypes.has(key)) {
      const { opts: keyOpts } = collectedTypes.get(key);
      const opt = {};
      if (keyOpts) {
        const { max, min } = keyOpts;
        if (max !== undefined) {
          opt.max = max;
        }
        if (min !== undefined) {
          opt.min = min;
        }
      }
      let type;
      switch (key) {
        case "angle":
        case "angle-percentage": {
          type = "angle";
          break;
        }
        case "integer":
        case "number": {
          type = "number";
          break;
        }
        case "length":
        case "length-percentage": {
          type = "length";
          break;
        }
        case "percentage": {
          type = "percentage";
          break;
        }
        default: {
          type = "dimension";
        }
      }
      opt.type = type;
      dimensions[type] = opt;
    }
  }
  if (Object.keys(dimensions).length) {
    opts.dimensionTypes = dimensions;
  }
  const functions = {};
  for (const type of functionTypes) {
    if (collectedTypes.has(type)) {
      functions[type] = type;
    }
  }
  if (Object.keys(functions).length) {
    opts.functionTypes = functions;
  }
  return opts;
}

/**
 * Collects CSS data types from a syntax definition.
 *
 * @param {string} syntax - The CSS syntax definition.
 * @returns {Map} The collection of types.
 */
function collectTypes(syntax) {
  const collectedTypes = new Map();
  if (!syntax) {
    return collectedTypes;
  }
  const ast = definitionSyntax.parse(syntax);
  if (ast.type === "Group") {
    const subTypeList = new Set();
    const propertyList = new Set();
    definitionSyntax.walk(ast, {
      enter(node) {
        const { name, type } = node;
        if (type === "Type") {
          if (typeList.has(name)) {
            collectedTypes.set(name, node);
          } else if (!name.endsWith("()")) {
            subTypeList.add(name);
          }
        } else if (type === "Property") {
          propertyList.add(name);
        }
      }
    });
    for (const type of subTypeList) {
      const typeKey = `<${type}>`;
      if (syntaxes.has(typeKey)) {
        const { syntax: typeSyntax } = syntaxes.get(typeKey);
        const expandedList = collectTypes(typeSyntax);
        for (const [key, value] of expandedList) {
          collectedTypes.set(key, value);
        }
      }
    }
    for (const property of propertyList) {
      if (definitions.has(property)) {
        const { syntax: propertySyntax } = definitions.get(property);
        const expandedList = collectTypes(propertySyntax);
        for (const [key, value] of expandedList) {
          collectedTypes.set(key, value);
        }
      }
    }
  }
  return collectedTypes;
}

/**
 * Utility to translate from `border-width` to `borderWidth`.
 * NOTE: For values prefixed with webkit, e.g. `-webkit-foo`, we need to provide
 * both `webkitFoo` and `WebkitFoo`. Here we only return `webkitFoo`.
 *
 * @param {string} dashed - The dashed property name.
 * @returns {string} The camel cased property name.
 */
function dashedToCamelCase(dashed) {
  if (dashed.startsWith("--")) {
    return dashed;
  }
  return dashed.replace(/^-(webkit)/, "$1").replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());
}
